variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool:
  vmImage: 'ubantu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(45b781f8-300f-4b51-8c66-feda52ed8d0e)'
    subscriptionId: '45b781f8-300f-4b51-8c66-feda52ed8d0e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMdeployment-rg'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: 'siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'